name: React App CI/CD

on:
  push:
    branches:
      - master # Run workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - master # Run workflow on pull requests to 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build # Build the app for production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/

      - name: Install Cypress
        run: npm install cypress --save-dev # Install Cypress

      - name: Start the React app
        run: npm start &
        env:
          CI: true # Ensures Create React App doesn't block Cypress

      - name: Wait for React app to be ready
        run: npx wait-on http://localhost:3001 # Wait for the app to be available

      - name: Run Cypress tests
        run: npx cypress run # Execute Cypress tests

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/
